data:
  train_path: data/Train_risk_classification_ans.csv
  test_paths: ['data/dev_risk.csv', 'data/test_risk.csv']
  pred_paths: ['output/decision.csv', 'output/pred_test_risk.csv']
  rand_remove: True

model:
  pretrained: DeepPavlov/bert-base-multilingual-cased-sentence

train_args:
  output_dir: runs/risk_pred

  per_device_train_batch_size: 2
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 16

  learning_rate: 0.00005
  weight_decay: 0.1
  num_train_epochs: 5
  lr_scheduler_type: linear
  warmup_ratio: 0.0

  save_strategy: epoch
  evaluation_strategy: epoch
  load_best_model_at_end: true
  seed: 7122
  report_to: none

  dataloader_num_workers: 0

  metric_for_best_model: eval_auroc

  label_smoothing_factor: 0.2
